apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: shopnow
  labels:
    app: shop-now
    type: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop-now
      type: backend
  template:
    metadata:
      labels:
        app: shop-now
        type: backend
    spec:
      containers:
        - name: backend
          image: 404931289118.dkr.ecr.us-east-1.amazonaws.com/shopnow-ecs/backend:latest
          ports:
            - containerPort: 5000
          env:
           - name: NODE_ENV
             value: production
           - name: DB_HOST
             value: shopnow-ecs-postgres.cmhe8m2yylg5.us-east-1.rds.amazonaws.com
           - name: DB_PORT
             value: "5432"
           - name: DB_NAME
             value: shopnow
           - name: DB_USER
             value: shopnow
           - name: DB_PASSWORD
             value: Niyongabo2006
           - name: DB_SSL
             value: "true"
           - name: REDIS_HOST
             value: shopnow-ecs-redis.scvcjh.0001.use1.cache.amazonaws.com
           - name: REDIS_PORT
             value: "6379"
           - name: PORT
             value: "5000"