apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: shopnow
  labels:
    app: shop-now
    type: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop-now
      type: backend
  template:
    metadata:
      labels:
        app: shop-now
        type: backend
    spec:
      containers:
        - name: backend
          image: ${BACKEND_IMAGE}
          ports:
            - containerPort: 5000
          env:
           - name: NODE_ENV
             value: production
           - name: DB_HOST
             value: ${DB_HOST}
           - name: DB_PORT
             value: "5432"
           - name: DB_NAME
             value: shopnow
           - name: DB_USER
             value: shopnow
           - name: DB_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: backend-secret
                 key: db-password
           - name: DB_SSL
             value: ${DB_SSL}
           - name: REDIS_HOST
             value: ${REDIS_HOST}
           - name: REDIS_PORT
             value: "6379"
           - name: PORT
             value: "5000"