apiVersion: v1
kind: Service
metadata:
  name: shopnow-backend
  namespace: shopnow
spec:
  selector:
    app: shop-now
    type: backend
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000


    
