apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: shopnow
  labels:
    app: shop-now
    type: frontend

spec:
  type: ClusterIP
  selector:
    app: shop-now
    type: frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000